In [6]:
import tensorflow as tf
import keras_preprocessing 
sequence = [[1], [2, 3], [4, 5, 6]]
seq1 = tf.keras.preprocessing.sequence.pad_sequences(sequence)
print(seq1)
seq2 =tf.keras.preprocessing.sequence.pad_sequences(sequence, value=-1)
print(seq2)

seq3 =tf.keras.preprocessing.sequence.pad_sequences(sequence, padding='post')
print(seq3)

seq4 =tf.keras.preprocessing.sequence.pad_sequences(sequence, maxlen=2)
print(seq4)


[[0 0 1]
 [0 2 3]
 [4 5 6]]
[[-1 -1  1]
 [-1  2  3]
 [ 4  5  6]]
[[1 0 0]
 [2 3 0]
 [4 5 6]]
[[0 1]
 [2 3]
 [5 6]]


Now I’ll use the label encoder method to convert the classes from strings to a numerical representation